name: "Setup development environment"
description: "Setup development environment for GitHub Actions"

runs:
  using: composite
  steps:
    - name: Setup | Mise
      uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3.5.0

    - name: Setup | Get pnpm cache directory
      id: pnpm-cache-dir
      shell: bash
      run: echo "dir=$(pnpm store path --silent)" >> ${GITHUB_OUTPUT}

    - name: Setup | Cache pnpm store
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: pnpm-cache
      with:
        path: ${{ steps.pnpm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Setup | Install dependencies
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: |
          args: [--frozen-lockfile, --strict-peer-dependencies]
