minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

saveExact: true

trustPolicy: no-downgrade

trustPolicyExclude:
  # eslint-plugin-reactがsemver v6に依存しているが、v6はOIDC認証がされていないためexcludeする
  - semver@6.3.1
