name: Changesets

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | GitHub App
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Setup | Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Run | Build
        run: pnpm run build

      - name: Run | Changesets
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          pr-title: "chore(release): publish"
          commit-message: "chore(release): publish"
          version-script: pnpm version-package
          publish-script: pnpm release
